/* I know, deleting all the fields is bad but I don't care */
/* DROP TABLE users, lots, spots, vehicles; */



CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text,
    pass_hash text,
    acct_type integer /* 0 = Driver, 1 = Owner */
);

CREATE TABLE lots (
    lot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id integer NOT NULL REFERENCES users,
    name text NOT NULL,
    address text NOT NULL,
    price integer NOT NULL,
		spaces_open integer NOT NULL
);


CREATE TABLE vehicles (
    vehicle_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id integer REFERENCES users,
    license_plate text NOT NULL,
    name text NOT NULL
);


CREATE TABLE reservations (
  reservation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	vehicle integer NOT NULL REFERENCES vehicles,
	lot integer NOT NULL REFERENCES lots,
	date timestamp without timezone NOT NULL DEFAULT current_timestamp,
	duration interval
);


